language: haskell
before_install:
    - sudo add-apt-repository -y ppa:h-rayflood/llvm
    - sudo apt-get update -qq
    # - sudo apt-get install --allow-unauthenticated -qq clang-3.4
install:
  # - cabal install hsc2hs cabal-dev
  # - cd engine && cabal install --only-dependencies --enable-tests
  - sh ./engine/tools/travis-ci-install.sh
  - cabal install split
script:
  # - cabal configure && cabal build && ./dist/build/shakefile/shakefile test
  - cd engine && ./stir update --force-reinstalls && ./stir test
env: PATH=/opt/llvm/bin CC=clang TOOLCHAIN_VARIANT=clang
